### ISSUE TITLE
Add services, MySQL users and privileges to backup script

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/Tools#31]
- database dump create schema (--skip-lock-tables, --databases <database>, --all-databases)
- MySQL users + privileges
- Services (csv export)
  - Apache - install via `httpd -k install -n "Apache"` (will give some error but work)
  - Athena (nssm) - "MySQL" dependency - delayed
  - Arma 3 Servers (nssm via setup script)
  - TeamSpeak 3 Server (nssm)
  - ...

**Comment by WSIContractor** [comment]
@jonpas It would be great to get more details on how the server is setup to provide connectivity from mysql to mission server? It appears that it is using something similar to a ARMA life server.

**Comment by jonpas** [comment]
That is an in-house things, but in bare-bones it's simply an extension.

And please, for the sake of being sane, don't compare Life to anything here! ;)

**Comment by WSIContractor** [comment]
My apologies. I did not mean anything from that. More the fact that you mention that it is an extension. Speaking architecturally wise that there is an extension connected to a database.

**Comment by jonpas** [comment]
No harm done, if you wish to discuss it further you can join our Slack and PM me there (link found on our website), but what is open-source is in https://github.com/Theseus-Aegis/tac-a3-mods and the rest is tailored specifically to work with our website as well, we have no plans of open-sourcing that (is also the core of what we do).

**Comment by WSIContractor** [comment]
Understood. It was a bit confusing that the project is open source, but parts are missing. So, it is hard to test things all up and see the complete solution.
