### ISSUE TITLE
Swifty_manage build all repos

### ISSUE THREAD

**Issue by Flyzoor** [Theseus-Aegis/Tools#51]
Possibility to build all repos at once with swifty_manage. Useful when updating all of them, as one can run it and step away for a few minutes.
Repo modlines should be printed out at the very end.

Discussion?

**Comment by jonpas** [comment]
> Possibility to build all repos at once with swifty_manage.

`python swifty_manage.py tac_core tac_sog`

> Repo modlines should be printed out at the very end.

No need, they are also written to an output file (specified with `-o --output`, default `swifty_manage_cfg.log`.
